ACCOUNT_ACTIVATION_DAYS = 1
PASSWORD_RESET_TIMEOUT_DAYS = 1

A2_REGISTRATION_EMAIL_IS_UNIQUE = True
A2_EMAIL_IS_UNIQUE = True

A2_USERNAME_LABEL = "Adresse e-mail"
A2_PROFILE_DISPLAY_EMPTY_FIELDS = True
A2_OPENED_SESSION_COOKIE_DOMAIN = "parent"
A2_NUMHOUSE_ERROR_MESSAGE = "Rentrez un format valide."
